### ISSUE TITLE
Telefunc Transform Error when building in CI steps

### ISSUE THREAD

**Issue by ebloom19** [brillout/telefunc#100]
I encounter the following error when building my project in my github Actions and when building in my Vercel automated deploy. 

Here is the stack trace: 

Error: [telefunc@0.1.71][Bug] You stumbled upon a bug in Telefunc's source code. Reach out at https://github.com/brillout/telefunc/issues/new or https://discord.com/invite/3DYWwk4xRQ and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes Telefunc more robust. Debug info (this is for the Telefunc maintainers; you can ignore this): {
  "telefuncFilePath": "/home/runner/work/acedit/acedit/packages/acedit-site/pages/demo/GetQuestionAudio.telefunc.ts",
  "sourceFiles": [
    "/__telefunc_typeToShield.ts",
    "/home/runner/work/acedit/acedit/packages/acedit-site/pages/demo/__telefunc_shieldGen_GetQuestionAudio.telefunc.ts"
  ],
  "tsConfigFilePath": "/home/runner/work/acedit/acedit/packages/acedit-site/tsconfig.json",
  "appRootDir": "/home/runner/work/acedit/acedit/packages/acedit-site"
}.
    at getProject (/home/runner/work/acedit/acedit/node_modules/telefunc/dist/cjs/node/server/shield/codegen/generateShield.js:75:28)
    at generateShield (/home/runner/work/acedit/acedit/node_modules/telefunc/dist/cjs/node/server/shield/codegen/generateShield.js:17:62)
    at transformTelefuncFileServerSide (/home/runner/work/acedit/acedit/node_modules/telefunc/dist/cjs/node/transformer/transformTelefuncFileServerSide.js:13:[52](https://github.com/ebloom19/acedit/actions/runs/8028560780/job/21933880131#step:9:53))
    at Object.transform (/home/runner/work/acedit/acedit/node_modules/telefunc/dist/cjs/node/vite/plugins/transform.js:29:24)
    at transform (file:///home/runner/work/acedit/acedit/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24367:16)
    at ModuleLoader.addModuleSource (file:///home/runner/work/acedit/acedit/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24[56](https://github.com/ebloom19/acedit/actions/runs/8028560780/job/21933880131#step:9:57)7:30) {
  code: 'PLUGIN_ERROR',
  plugin: 'telefunc:transform',
  hook: 'transform',
  id: '/home/runner/work/acedit/acedit/packages/acedit-site/pages/demo/GetQuestionAudio.telefunc.ts',

**Comment by brillout** [comment]
It seems that your file `/home/runner/work/acedit/acedit/packages/acedit-site/pages/demo/GetQuestionAudio.telefunc.ts` isn't included by your `/home/runner/work/acedit/acedit/packages/acedit-site/tsconfig.json`: make sure all your Telefunc files match `tsconfig.json#include` (and don't match `tsconfig.json#exclude`).

Let me know whether you find the issue.

**Comment by brillout** [comment]
FYI your `tsconfig.json` doesn't match any of your TypeScript file. (The two files listed in `"sourceFiles"` are added by Telefunc.)
