### ISSUE TITLE
telefunc vite without express

### ISSUE THREAD

**Issue by Hima-Pro** [brillout/telefunc#108]
Hello,
how to use telefunc with vite but without express.js. When I run the vite app with vite preview after build, I get a 500 error for telefunc functions. Is this a known issue, and is there a workaround?

here is the error from the terminal:
```
$ vite preview --host
  ➜  Local:   http://localhost:8000/
  ➜  Network: http://192.168.131.148:8000/
  ➜  Network: http://172.0.0.1:8000/
  ➜  press h + enter to show help
Error: [@brillout/vite-plugin-server-entry@0.4.6][Bug] You stumbled upon a bug in the source code of @brillout/vite-plugin-server-entry. Reach out at https://github.com/brillout/vite-plugin-server-entry/issues/new and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes @brillout/vite-plugin-server-entry more robust.
    at importServerEntry (/media/ibrahim/MyFiles/htdocs/Projects/web-balancer/node_modules/@brillout/vite-plugin-server-entry/dist/importServerEntry/index.js:38:28)
    at loadGlobImporter (/media/ibrahim/MyFiles/htdocs/Projects/web-balancer/node_modules/telefunc/dist/cjs/node/vite/loadTelefuncFilesWithVite.js:37:61)
    at async loadTelefuncFilesWithVite (/media/ibrahim/MyFiles/htdocs/Projects/web-balancer/node_modules/telefunc/dist/cjs/node/vite/loadTelefuncFilesWithVite.js:10:45)
    at async loadTelefuncFiles (/media/ibrahim/MyFiles/htdocs/Projects/web-balancer/node_modules/telefunc/dist/cjs/node/server/runTelefunc/loadTelefuncFiles.js:34:73)
    at async runTelefunc_ (/media/ibrahim/MyFiles/htdocs/Projects/web-balancer/node_modules/telefunc/dist/cjs/node/server/runTelefunc.js:83:59)
    at async runTelefunc (/media/ibrahim/MyFiles/htdocs/Projects/web-balancer/node_modules/telefunc/dist/cjs/node/server/runTelefunc.js:38:16)
    at async telefunc (/media/ibrahim/MyFiles/htdocs/Projects/web-balancer/node_modules/telefunc/dist/cjs/node/server/telefunc.js:11:26)
```

**Comment by brillout** [comment]
I don’t think it makes sense to be able to use Telefunc without a
production server? I don’t see a use case for using Telefunc without some
kind of sever-side runtime.
