### ISSUE TITLE
Server files being included in vite client bundle

### ISSUE THREAD

**Issue by stephen-dahl** [brillout/telefunc#133]
I am using telefunc with vite and everything was going great while deving.
When I build i get errors with vite trying to include my telefunc fn includes into the client bundle.

for example
```typescript
//my.telefunc.ts
import { sql } from '@lib/api/sql';
export const load = async (orgEntityId: string) => {
  return sql`SELECT * FROM myTable...`;
}
```

```typescript
//@lib/api/sql.ts
import postgres from 'postgres';
import config from '../../server/config';

export const sql = postgres({
  host: config.pgHost,
  port: config.pgPort,
  database: 'read',
  username: config.pgUser,
  password: config.pgPass,
  transform: postgres.camel,
});
```

this works when deving but when `vite build` I get errors about including postgres in the client bundle
```
[plugin:vite:resolve] [plugin vite:resolve] Module "os" has been externalized for browser compatibility, imported by "/Users/stephen/code/frontend/app/node_modules/postgres/src/index.js". See https://vite.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] [plugin vite:resolve] Module "fs" has been externalized for browser compatibility, imported by "/Users/stephen/code/frontend/app/node_modules/postgres/src/index.js". See https://vite.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] [plugin vite:resolve] Module "net" has been externalized for browser compatibility, imported by "/Users/stephen/code/frontend/app/node_modules/postgres/src/connection.js". See https://vite.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] [plugin vite:resolve] Module "tls" has been externalized for browser compatibility, imported by "/Users/stephen/code/frontend/app/node_modules/postgres/src/connection.js". See https://vite.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] [plugin vite:resolve] Module "crypto" has been externalized for browser compatibility, imported by "/Users/stephen/code/frontend/app/node_modules/postgres/src/connection.js". See https://vite.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] [plugin vite:resolve] Module "stream" has been externalized for browser compatibility, imported by "/Users/stephen/code/frontend/app/node_modules/postgres/src/connection.js". See https://vite.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] [plugin vite:resolve] Module "perf_hooks" has been externalized for browser compatibility, imported by "/Users/stephen/code/frontend/app/node_modules/postgres/src/connection.js". See https://vite.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] [plugin vite:resolve] Module "stream" has been externalized for browser compatibility, imported by "/Users/stephen/code/frontend/app/node_modules/postgres/src/large.js". See https://vite.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```

vite.config.ts
```typescript
import UnpluginTypia from '@ryoppippi/unplugin-typia/vite';
import { TanStackRouterVite } from '@tanstack/router-plugin/vite';
import react from '@vitejs/plugin-react-swc';
import { dirname, resolve } from 'path';
import { telefunc } from 'telefunc/vite';
import { fileURLToPath } from 'url';
import { defineConfig } from 'vite';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    UnpluginTypia(),
    telefunc(),
    TanStackRouterVite({
      routeFileIgnorePattern: '^(?!(__root|index|route)(\\.lazy)?\\.tsx$).*\\.tsx?$',
    }),
    react(),
  ],
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
      '@lib': resolve(__dirname, 'src/lib'),
      '@components': resolve(__dirname, 'src/components'),
    },
  },
  worker: {
    format: 'es',
  },
  build: {
    target: 'es2023',
    rollupOptions: {
      output: { format: 'es' },
    },
  },
});
```

**Comment by stephen-dahl** [comment]
realized i didnt include the actual error

```
✓ 5425 modules transformed.
x Build failed in 14.60s
error during build:
[vite:worker-import-meta-url] node_modules/postgres/src/connection.js (5:9): "performance" is not exported by "__vite-browser-external", imported by "node_modules/postgres/src/connection.js".
file: /Users/stephen/code/frontend/app/src/routes/$orgId/contract-builder/fee-schedule-imports/$id/FileReader.ts:5:9

3: import crypto from 'crypto'
4: import Stream from 'stream'
5: import { performance } from 'perf_hooks'
            ^
6: 
7: import { stringify, handleValue, arrayParser, arraySerializer } from './types.js'

    at getRollupError (file:///Users/stephen/code/frontend/app/node_modules/rollup/dist/es/shared/parseAst.js:393:41)
    at error (file:///Users/stephen/code/frontend/app/node_modules/rollup/dist/es/shared/parseAst.js:389:42)
    at Module.error (file:///Users/stephen/code/frontend/app/node_modules/rollup/dist/es/shared/node-entry.js:14900:16)
    at Module.traceVariable (file:///Users/stephen/code/frontend/app/node_modules/rollup/dist/es/shared/node-entry.js:15347:29)
    at ModuleScope.findVariable (file:///Users/stephen/code/frontend/app/node_modules/rollup/dist/es/shared/node-entry.js:13248:39)
    at FunctionScope.findVariable (file:///Users/stephen/code/frontend/app/node_modules/rollup/dist/es/shared/node-entry.js:5221:38)
    at FunctionBodyScope.findVariable (file:///Users/stephen/code/frontend/app/node_modules/rollup/dist/es/shared/node-entry.js:5221:38)
    at FunctionScope.findVariable (file:///Users/stephen/code/frontend/app/node_modules/rollup/dist/es/shared/node-entry.js:5221:38)
    at FunctionBodyScope.findVariable (file:///Users/stephen/code/frontend/app/node_modules/rollup/dist/es/shared/node-entry.js:5221:38)
    at MemberExpression.bind (file:///Users/stephen/code/frontend/app/node_modules/rollup/dist/es/shared/node-entry.js:6860:49)
error: script "build" exited with code 1
```

**Comment by stephen-dahl** [comment]
the file it mentions includes a web worker witch would start a new bundle. that bundle doesn't use any telefuncs

**Comment by brillout** [comment]
I'll need a minimal reproduction, I'll re-open then.

**Comment by stephen-dahl** [comment]
i had includes like
`const Component = self.document ? (await import('./Component')).default : () => null;`
I don't know why a conditional import that prevents component code from being loaded in web workers with a component that does not use telefunc caused this but removing these is what fixed it for me.
