### ISSUE TITLE
Nuxt 3: Cannot find module './telefunc'

### ISSUE THREAD

**Issue by Kimbo0o** [brillout/telefunc#41]
Hi,

I tried setting up a new Nuxt 3 Project and rebuilding the Nuxt 2 example within it. Right now I have a problem with an import that I could also reproduce within the following StackBlitz:
[https://stackblitz.com/edit/nuxt-starter-yuyqpd?file=package.json]()

``` bash
[nuxt] [request error] [unhandled] [500] Cannot find module './telefunc'
Require stack:
- /home/projects/nuxt-starter-yuyqpd/telefunc
  at Module._resolveFilename (https://nuxt-starter-yuyqpd.w.staticblitz.com/blitz.3e4f172269cb19a250be0dfdff1ab657cb850d0e.js:6:217308)  
  at Module._load (https://nuxt-starter-yuyqpd.w.staticblitz.com/blitz.3e4f172269cb19a250be0dfdff1ab657cb850d0e.js:6:214847)  
  at Module.require (https://nuxt-starter-yuyqpd.w.staticblitz.com/blitz.3e4f172269cb19a250be0dfdff1ab657cb850d0e.js:6:218087)  
  at i (https://nuxt-starter-yuyqpd.w.staticblitz.com/blitz.3e4f172269cb19a250be0dfdff1ab657cb850d0e.js:6:415284)  
  at eval (telefunc:4:18)  
  at ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:268:11)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:145:12)  
  at async request (./node_modules/vite-node/dist/client.mjs:168:16)  
  at async eval (./auth/getUser.js:1:238)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:268:5)
```

Does anyone have an idea how this could be solved?
I would like to include my example in the docs once I get it to work.

**Comment by brillout** [comment]
Hm, at first sight it seems like a problem on Nuxt's side? I'm not all too familiar with Nuxt 3.
