### ISSUE TITLE
Vike Project throws the following error when invoking Telefunc in Vercel Serverless Function

### ISSUE THREAD

**Issue by rdelacrz** [brillout/telefunc#92]
Got the following error message while trying to set up a Vike project configured with Vercel serverless apis with telefunc in it:

Error: [telefunc@0.1.62][Bug] You stumbled upon a bug in Telefunc's source code. Reach out at https://github.com/brillout/telefunc/issues/new or https://discord.com/invite/3DYWwk4xRQ and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes Telefunc more robust.
    at loadGlobImporter (B:\Programming\Workspace\blood-destiny-site\node_modules\telefunc\dist\cjs\node\vite\loadTelefuncFilesWithVite.js:39:32)
    at async loadTelefuncFilesWithVite (B:\Programming\Workspace\blood-destiny-site\node_modules\telefunc\dist\cjs\node\vite\loadTelefuncFilesWithVite.js:10:45)
    at async loadTelefuncFiles (B:\Programming\Workspace\blood-destiny-site\node_modules\telefunc\dist\cjs\node\server\runTelefunc\loadTelefuncFiles.js:34:73)
    at async runTelefunc_ (B:\Programming\Workspace\blood-destiny-site\node_modules\telefunc\dist\cjs\node\server\runTelefunc.js:82:59)
    at async runTelefunc (B:\Programming\Workspace\blood-destiny-site\node_modules\telefunc\dist\cjs\node\server\runTelefunc.js:38:16)
    at async telefunc (B:\Programming\Workspace\blood-destiny-site\node_modules\telefunc\dist\cjs\node\server\telefunc.js:11:26)
    at async default (file:///B:/Programming/Workspace/blood-destiny-site/api/telefunc.js:11:24)

**Comment by rdelacrz** [comment]
Interestingly enough, the issue seemed to have fixed itself. Not sure what happened, but maybe it was an issue on the Vercel side? I'll close this since it doesn't seem like I have issues anymore.
